Document: plasma-runner-cliprunner
Title: Debian plasma-runner-cliprunner Manual
Author: <insert document author here>
Abstract: This manual describes what plasma-runner-cliprunner is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/plasma-runner-cliprunner/plasma-runner-cliprunner.sgml.gz

Format: postscript
Files: /usr/share/doc/plasma-runner-cliprunner/plasma-runner-cliprunner.ps.gz

Format: text
Files: /usr/share/doc/plasma-runner-cliprunner/plasma-runner-cliprunner.text.gz

Format: HTML
Index: /usr/share/doc/plasma-runner-cliprunner/html/index.html
Files: /usr/share/doc/plasma-runner-cliprunner/html/*.html
